//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookLocation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shelf
    {
        public int id { get; set; }
        public int floor { get; set; }
        public string selection { get; set; }
        public int row { get; set; }
        public int col { get; set; }
        public string side { get; set; }
        public int shelfFloor { get; set; }
        public string rfidCode { get; set; }
    }
}
